from enum import IntEnum


class CANID(IntEnum):

    SYSTEM_STATUS = 0xFF00
    ELECTRICAL_STATUS = 0xFF01
    CURRENT_STATUS = 0xFF02
    EXCITER_STATUS = 0xFF03
    THERMAL_STATUS = 0xFF04
    BIT_STATUS = 0xFF05
    HEALTH_STATUS = 0xFF06
    PROTECTION_STATUS = 0xFF07
    FAULT_STATUS = 0xFF08

    FAULT_EVENT = 0xFF09

    COMMAND_CONTROL = 0xFF20
    PARAMETER_ACCESS = 0xFF21